# **Theoretical Questions:**

**1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?**

Purpose of NumPy in Scientific Computing and Data Analysis


NumPy (Numerical Python) is a fundamental library in Python for performing numerical operations efficiently. It provides support for multi-dimensional arrays, matrices, and mathematical functions, making it essential in scientific computing and data analysis. NumPy enhances Python by offering fast and reliable operations on large datasets, which would be cumbersome to achieve using native Python lists or loops.



In [ ]:
Key Advantages of NumPy

1.Performance and Speed

a.Faster than Python lists: NumPy arrays use contiguous memory and are optimized for numerical operations, resulting in faster execution.
b.Vectorization: Allows operations to be applied to entire arrays without the need for explicit loops, reducing overhead.

In [ ]:
2.Efficient Memory Management

a.Fixed-type arrays: NumPy arrays store elements of the same data type, making them more memory-efficient compared to heterogeneous Python lists.
b.Compact storage: Since the data types are fixed, NumPy uses less memory than equivalent Python data structures.

In [ ]:
3.Multi-dimensional Array Support

a.Supports arrays with multiple dimensions (1D, 2D, or nD), which are crucial for matrix operations, image data processing, and scientific simulations.

In [ ]:
4.Broadcasting

a.Broadcasting rules allow arithmetic operations between arrays of different shapes and sizes without requiring explicit loops or dimension matching.

In [ ]:
5.Extensive Mathematical Functions

a.Includes optimized implementations of linear algebra (dot products, matrix inversions), statistical operations (mean, standard deviation), and Fourier transforms, saving developers time from building these tools from scratch.

In [ ]:
6.Interoperability with Other Libraries

a.Many popular libraries such as Pandas, SciPy, TensorFlow, and scikit-learn use NumPy arrays as their underlying data structure. This makes data exchange between libraries seamless.

In [ ]:
7.Random Number Generation

a.The numpy.random module provides powerful tools for generating random numbers and working with distributions, useful for simulations and statistical analysis.

In [ ]:
8.Ease of Use and Community Support

a.NumPy has intuitive syntax for array creation and manipulation, with well-maintained documentation and a large community for support.

In [ ]:
How NumPy Enhances Python’s Capabilities

1.Numerical Computations on Large Data

a.Python lists are inefficient for large-scale data processing. With NumPy, operations such as element-wise addition, matrix multiplication, or statistical summaries can be performed in constant or near-linear time.

In [ ]:
2.Vectorized Operations for Cleaner Code

a.Instead of looping through elements manually (as you would with Python lists), NumPy supports vectorized operations. For example:

In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b  # Vectorized addition
print(result)

[5 7 9]


In [ ]:
3.Parallel Processing and BLAS/LAPACK Integration

a.NumPy can internally leverage BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package) libraries for optimized matrix computations, providing better performance through parallel processing.

In [ ]:
4.Handling Multi-Dimensional Data Easily

a.Python lists require nested loops to handle multi-dimensional data, while NumPy simplifies this by abstracting these complexities into efficient array structures

**2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?**

Comparison of np.mean() and np.average() in NumPy
Both np.mean() and np.average() are functions used to compute the central tendency of numerical data, but they have key differences in terms of functionality, usage, and behavior. Below is a detailed comparison of the two functions, along with guidance on when to use each

In [ ]:
1. np.mean()
Purpose: Calculates the arithmetic mean (simple average) of the input data.

Syntax:

In [ ]:
np.mean(a, axis=None, dtype=None, out=None, keepdims=False)

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))

2.5


In [ ]:
2. np.average()
Purpose: Calculates a weighted average of the input data. If no weights are provided, it behaves the same as np.mean().

Syntax:

In [ ]:
np.average(a, axis=None, weights=None, returned=False)

In [4]:
arr = np.array([1, 2, 3, 4])
weights = np.array([0.1, 0.2, 0.3, 0.4])
print(np.average(arr, weights=weights))

3.0


**3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays**

Reversing a NumPy Array along Different Axes
Reversing an array means rearranging its elements in the opposite order along a specific axis. NumPy provides several ways to reverse arrays, whether they are 1D or multi-dimensional (e.g., 2D). Below are different techniques with examples for reversing arrays.



In [ ]:
1. Reversing a 1D Array
A 1D array is a single sequence of elements.

Method 1: Using Slicing ([::-1])
This is the simplest and most efficient way to reverse a 1D array.

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


In [ ]:
2. Reversing a 2D Array
In a 2D array, you can reverse elements along different axes.

Method 1: Reversing along Rows (axis=1)
This method reverses the elements within each row (i.e., horizontally).

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

reversed_rows = arr[:, ::-1]
print(reversed_rows)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
Method 2: Reversing along Columns (axis=0)
This method flips the rows vertically.

In [7]:
reversed_columns = arr[::-1, :]
print(reversed_columns)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
3. Using np.flip() Function
NumPy provides the np.flip() function, which can reverse arrays along a specified axis.

Example 1: Reversing a 1D Array using np.flip()

In [8]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = np.flip(arr)
print(reversed_arr)

[5 4 3 2 1]


In [ ]:
Example 2: Reversing a 2D Array along Rows (axis=0)

In [9]:
reversed_columns = np.flip(arr, axis=0)
print(reversed_columns)

[5 4 3 2 1]


**4.How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.**

How to Determine the Data Type of Elements in a NumPy Array

In NumPy, data type (also known as dtype) refers to the type of elements stored in the array (e.g., integers, floats, booleans). Knowing the data type is important for efficient memory usage and performance optimization. NumPy provides several ways to inspect the data type of elements in an array.

In [ ]:
1. Methods to Check the Data Type
Method 1: Using .dtype Attribute
You can directly access the dtype attribute to determine the type of the elements in the array.

In [13]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)

int64


In [ ]:
Method 2: Using type() Function
Use type() to check the type of the NumPy array object itself.

In [14]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
Method 3: Checking the Data Type of Individual Elements
Use type() or arr.dtype.type to check the type of a specific element.

In [15]:
print(type(arr[0]))
print(arr.dtype.type)

<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Method 4: np.issubdtype() to Check Data Type Hierarchy
Use this function to compare the data type against a broader category (e.g., checking if it's an integer).

In [16]:
print(np.issubdtype(arr.dtype, np.integer))

True


In [ ]:
Importance of Data Types in Memory Management and Performance\

The data type of elements in a NumPy array plays a crucial role in how efficiently the array consumes memory and performs computations.

1. Memory Management

a.Memory Efficiency: NumPy arrays store elements in contiguous memory blocks, unlike Python lists, which store references to objects.

b.For example, int32 requires 4 bytes per element, whereas int64 needs 8 bytes. Choosing the right data type ensures that no excess memory is used.

In [ ]:
arr_32 = np.array([1, 2, 3], dtype=np.int32)  # Uses 12 bytes (3 * 4)
arr_64 = np.array([1, 2, 3], dtype=np.int64)  # Uses 24 bytes (3 * 8)

In [ ]:
Trade-off Between Size and Precision:

Storing data in a larger data type (e.g., float64) provides higher precision, but at the cost of more memory usage.

In [ ]:
2. Performance Optimization
a.Faster Computations: Smaller data types (e.g., int32) perform faster operations because they consume less memory and fit better into CPU cache.

   Example: If you only need integers up to a few thousand, using int32 would be faster than int64.

b.Consistency Across Operations: Many NumPy functions rely on consistent dtype for performance. If data types need to be cast during computation (e.g., mixing float32 and float64), the performance drops.

c.Avoiding Overflow: When working with large datasets, choosing an inappropriate data type can lead to overflow errors.

   Example: Adding large numbers with int8 (which can only store values between -128 and 127) will result in incorrect values.

In [ ]:
Choosing the Right Data Type: Key Considerations

1.Numeric Precision vs. Memory Usage:

  Use float32 instead of float64 if less precision is sufficient.
2.Performance Needs:

  If the operations are intensive, prefer smaller data types (like int32 or float32) to reduce memory footprint and improve speed.
3.Avoiding Type Casting:

  Use the same dtype across arrays to avoid unnecessary upcasting or downcasting during operations.

**5.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists**

What are ndarrays in NumPy?

In NumPy, an ndarray (short for n-dimensional array) is the core data structure used for storing data in a homogeneous, multi-dimensional array. It allows for fast and efficient operations on large datasets by leveraging contiguous memory and optimized mathematical functions.


In [ ]:
Key Features of ndarray in NumPy
`1.Homogeneous Data:

All elements in an ndarray must be of the same data type (e.g., integers, floats). This ensures memory efficiency and faster computation.

In [ ]:
2.N-Dimensional:

a.ndarray can represent data in 1D, 2D, or more dimensions (e.g., vectors, matrices, or tensors).
b.Example:
1D: [1, 2, 3]
2D: [[1, 2], [3, 4]]
3D: A stack of matrices.

In [ ]:
3.Fixed Size:

Once created, the size (or shape) of an ndarray is fixed. You can reshape or create new arrays but cannot change the size of an existing array in-place.

In [ ]:
4.Efficient Memory Management:

Arrays are stored in contiguous blocks of memory, allowing faster access and better CPU cache utilization compared to Python lists.

In [ ]:
5.Broadcasting and Vectorized Operations:

a.NumPy supports broadcasting, which allows element-wise operations between arrays of different shapes without explicit loops.

bIt also supports vectorized operations, performing operations on entire arrays instead of individual elements.

In [ ]:
6.Rich Functionality:

NumPy provides functions for sorting, filtering, reshaping, aggregating, and performing linear algebra operations efficiently.

In [ ]:
7.Built-in Methods for Mathematical Operations:

Operations such as addition, subtraction, multiplication, dot product, and statistical functions are optimized for ndarrays.

In [18]:
import numpy as np

# Create a 2D ndarray
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(f"Shape: {arr.shape}")
print(f"Data type: {arr.dtype}")

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data type: int64


**6.Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

Performance Benefits of NumPy Arrays over Python Lists for Large-Scale Numerical Operations

When working with large datasets, NumPy arrays offer significant performance advantages over Python lists. This efficiency comes from how NumPy handles memory management, operations, and data structures under the hood. Below is a detailed analysis of the performance benefits of NumPy arrays.

In [ ]:
Key Performance Benefits of NumPy Arrays

1. Memory Efficiency

a.Fixed Data Types:

  1.NumPy arrays store elements of the same data type (e.g., int32, float64). This reduces memory overhead since there are no per-element type checks or object references, unlike Python lists, which store elements as individual objects.

  2.Example: A Python list [1, 2, 3] stores references to three separate integer objects, while a NumPy array holds the raw values contiguously in memory.

In [ ]:
2.Compact Storage:

a.A NumPy array with 10 million integers (int32) requires only 40 MB (10 million × 4 bytes), while a Python list of the same size takes around 100 MB or more due to the overhead of storing references to Python objects.

In [ ]:
2. Contiguous Memory Layout (Cache-Friendly)

a.Cache Optimization:

  1.NumPy arrays are stored in contiguous blocks of memory, allowing the CPU to fetch multiple elements at once into its cache. This improves performance, especially for large datasets, because fewer memory accesses are required.

b.Python Lists:

  1.Python lists store elements as disjoint objects in memory, with references to their locations. This increases cache misses and slows down data access.

In [ ]:
3. Vectorized Operations (Elimination of Python Loops)
a.Vectorization:

 1.NumPy allows you to perform element-wise operations (like addition or multiplication) without explicit Python loops. These operations are optimized at a low level (C/Fortran), making them significantly faster.

In [ ]:
import numpy as np
size = 10**6  # One million elements

# Python list addition
a = list(range(size))
b = list(range(size))
%timeit [a[i] + b[i] for i in range(size)]  # Slow due to Python loop

# NumPy array addition
arr_a = np.array(a)
arr_b = np.array(b)
%timeit arr_a + arr_b  # Much faster due to vectorization

In [ ]:
4. Reduced Overhead of Function Calls

1.Single Operation Execution:

 a.When working with Python lists, each arithmetic operation or transformation involves multiple function calls in Python (e.g., looping through elements, applying operations). This overhead is avoided with NumPy, which applies operations directly to the entire array in a single step.

In [ ]:
2.Batch Processing:

a.NumPy processes entire arrays at once (batch operations), reducing the need for interpreted code execution, which speeds up large-scale computations.

In [ ]:
5. Parallel Processing with BLAS/LAPACK Libraries

a.Optimized Linear Algebra Operations:

 1.NumPy integrates with BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra PACKage) libraries, which are highly optimized and can exploit multi-core processors. This makes matrix operations (e.g., dot products, matrix inversions) much faster compared to manual implementations in Python lists.

In [ ]:
# NumPy matrix multiplication using dot product
A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)
%timeit np.dot(A, B)  # Uses optimized BLAS routines

In [ ]:
6. Type Safety and Avoiding Overhead of Type Checking

a.No Dynamic Type Checking:

 1.Python lists store heterogeneous elements, requiring type checks at runtime for each element during operations. This introduces performance overhead.

 2.In contrast, NumPy arrays are homogeneous and operate on fixed types, avoiding unnecessary type checking during operations, leading to faster execution.

In [ ]:
7. Broadcasting Support for Efficient Computations

Broadcasting allows NumPy to apply operations to arrays of different shapes without copying or expanding the data, saving both memory and time.

In [19]:
arr = np.array([1, 2, 3])
matrix = np.array([[10, 20, 30], [40, 50, 60]])
result = matrix + arr  # Broadcasting applied automatically
print(result)

[[11 22 33]
 [41 52 63]]


**7.Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output**

In [ ]:
Comparing vstack() and hstack() Functions in NumPy

The vstack() and hstack() functions in NumPy are used to stack arrays along specific axes. While both are helpful in combining arrays, they differ in how they align the input arrays: vstack() stacks vertically (row-wise), and hstack() stacks horizontally (column-wise). Below is a detailed comparison with examples.

In [ ]:
1. np.vstack() - Vertical Stacking

a.Purpose:

1.Stacks arrays vertically by adding them as new rows.
2.Input arrays are combined along axis 0 (the row axis).

b.Requirement:

1.Arrays must have the same number of columns to be vertically stacked.

In [ ]:
Example 1: Stacking 1D Arrays

In [21]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
Example 2: Stacking 2D Arrays Vertically

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9]])

result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
2. np.hstack() - Horizontal Stacking

a.Purpose:

1.Stacks arrays horizontally by adding new columns.
2.Input arrays are combined along axis 1 (the column axis).

b.Requirement:

1.Arrays must have the same number of rows to be horizontally stacked.

In [ ]:
Example 1: Stacking 1D Arrays

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print(result)

[1 2 3 4 5 6]


In [ ]:
Example 2: Stacking 2D Arrays Horizontally

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

result = np.hstack((a, b))
print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**8.Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions**

Differences Between fliplr() and flipud() in NumPy
The fliplr() and flipud() methods in NumPy are used to flip arrays along specific axes. Both functions reverse the order of elements, but they differ in which axis the flipping occurs. Below is a detailed comparison of these methods, along with examples to show how they behave with different array dimensions.

In [ ]:
1. np.fliplr() - Flip Left to Right (Horizontal Flip)

a.Purpose:

 1.Reverses the columns of a 2D array or matrix, flipping it left to right.
 2.It does not affect the row order.

b.Applicable to:

 1.Only 2D arrays (or higher-dimensional arrays with at least two dimensions).

In [ ]:
Example 1: Using fliplr() on a 2D Array

In [25]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = np.fliplr(arr)
print(result)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
Example 2: Using fliplr() on a Higher-Dimensional Array

In [26]:
arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

result = np.fliplr(arr)
print(result)

[[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]


In [ ]:
2. np.flipud() - Flip Up to Down (Vertical Flip)

a.Purpose:

 1.Reverses the rows of a 2D array or matrix, flipping it up to down.
 2.It does not affect the column order.

b.Applicable to:

 1.1D, 2D, or higher-dimensional arrays.

In [ ]:
Example 1: Using flipud() on a 2D Array

In [27]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = np.flipud(arr)
print(result)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
Example 2: Using flipud() on a 1D Array

In [28]:
arr = np.array([1, 2, 3, 4, 5])

result = np.flipud(arr)
print(result)

[5 4 3 2 1]


**9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

array_split() Method in NumPy: Functionality and Handling of Uneven Splits

The np.array_split() function in NumPy is used to split an array into multiple sub-arrays. It’s particularly useful when you need to partition an array into a specified number of chunks. One of the key features of array_split() is its ability to handle uneven splits, distributing leftover elements intelligently.

In [ ]:
Syntax of array_split()

numpy.array_split(ary, indices_or_sections, axis=0)

In [ ]:
Functionality and Examples

1. Splitting Evenly

If the input array can be divided evenly by the specified number of splits, array_split() works similarly to np.split().

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
result = np.array_split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
2. Handling Uneven Splits

When the array cannot be divided evenly, array_split() distributes the leftover elements across the smaller chunks. The extra elements are assigned to the earlier sub-arrays.

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
result = np.array_split(arr, 3)
print(result)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [ ]:
3. Specifying Indices for Split Points

Instead of giving the number of parts, you can specify the indices where the array should be split.

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
result = np.array_split(arr, [2, 5])
print(result)

[array([1, 2]), array([3, 4, 5]), array([6, 7])]


In [ ]:
4. Splitting Along Different Axes

By default, array_split() splits the array along axis 0 (rows). You can change the axis parameter to split along different axes.

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.array_split(arr, 2, axis=1)
print(result)

[array([[1, 2],
       [4, 5]]), array([[3],
       [6]])]


**10.Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?**

Concepts of Vectorization and Broadcasting in NumPy
In NumPy, vectorization and broadcasting are two core techniques that contribute to efficient array operations by minimizing the use of explicit loops and making operations faster. These features leverage low-level optimizations to execute mathematical operations on large datasets efficiently, enabling better memory usage and faster computation times.

In [ ]:
1. Vectorization in NumPy

What is Vectorization?

Vectorization refers to the process of replacing explicit loops with array-based operations in NumPy. This allows operations to be performed on entire arrays or batches of data simultaneously, taking advantage of compiled low-level code (written in C/Fortran) under the hood.

How Vectorization Works:

In a non-vectorized approach, we would use loops to iterate over each element of an array. In NumPy, vectorization enables us to apply operations directly on arrays without using Python-level loops.

In [ ]:
Example of Vectorization: Element-wise Addition

Without Vectorization (Using a Loop)

In [33]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
result = []

for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)

[6, 8, 10, 12]


In [ ]:
With Vectorization (Using NumPy)

In [34]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
result = a + b

print(result)

[ 6  8 10 12]


In [ ]:
2. Broadcasting in NumPy

What is Broadcasting?

1.Broadcasting is a technique that allows arrays of different shapes to be used together in arithmetic operations. Instead of explicitly reshaping arrays, NumPy automatically expands the smaller array to match the shape of the larger array during operations.

2.Broadcasting eliminates the need to duplicate data or manually reshape arrays, saving both time and memory.

In [ ]:
Example 1: Broadcasting a 1D Array to a 2D Array

In [36]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
vec = np.array([10, 20, 30])            # Shape: (3,)

result = arr + vec
print(result)

[[11 22 33]
 [14 25 36]]


In [ ]:
Example 2: Broadcasting Scalars

In [37]:
arr = np.array([1, 2, 3])
result = arr * 2

print(result)

[2 4 6]


In [ ]:
Example 3: Incompatible Shapes (Broadcasting Error)

In [ ]:
a = np.array([1, 2, 3])  # Shape: (3,)
b = np.array([4, 5])     # Shape: (2,)

# This will raise a ValueError because the shapes are not compatible.
result = a + b

# Practical Questions:

**1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

Here is the original 3x3 NumPy array with random integers between 1 and 100, along with the interchanged version (transposed):

In [ ]:
Original Array:

In [ ]:
[[52 93 15]
 [72 61 21]
 [83 87 75]]

In [ ]:
Interchanged Array (Rows ↔ Columns):

In [ ]:
[[52 72 83]
 [93 61 87]
 [15 21 75]]

**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array**

In [ ]:
1D Array (Original):

In [ ]:
[0 1 2 3 4 5 6 7 8 9]

In [ ]:
2x5 Array (After Reshaping):

In [ ]:
[[0 1 2 3 4]
 [5 6 7 8 9]]

In [ ]:
5x2 Array (After Reshaping):

In [ ]:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

**3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [ ]:
Original 4x4 Array with Random Floats:

In [ ]:
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]]

In [ ]:
6x6 Array with a Border of Zeros:

In [ ]:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.37454012 0.95071431 0.73199394 0.59865848 0.        ]
 [0.         0.15601864 0.15599452 0.05808361 0.86617615 0.        ]
 [0.         0.60111501 0.70807258 0.02058449 0.96990985 0.        ]
 [0.         0.83244264 0.21233911 0.18182497 0.18340451 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]

**4.Using NumPy, create an array of integers from 10 to 60 with a step of 5**

In [38]:
import numpy as np

# Create the array using np.arange
arr = np.arange(10, 61, 5)

# Print the array
print("Array from 10 to 60 with step 5:", arr)

Array from 10 to 60 with step 5: [10 15 20 25 30 35 40 45 50 55 60]


**5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element**

In [39]:
import numpy as np

# Create the NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply case transformations
uppercase_arr = np.char.upper(arr)   # Convert to uppercase
lowercase_arr = np.char.lower(arr)   # Convert to lowercase
titlecase_arr = np.char.title(arr)   # Convert to title case
capitalize_arr = np.char.capitalize(arr)  # Capitalize first letter

# Print the results
print("Original Array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Title Case:", titlecase_arr)
print("Capitalized:", capitalize_arr)

Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalized: ['Python' 'Numpy' 'Pandas']


**6.Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [40]:
import numpy as np

# Create a NumPy array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_arr = np.char.join(' ', arr)

# Print the result
print("Original Array:", arr)
print("Array with Spaces Between Characters:", spaced_arr)

Original Array: ['python' 'numpy' 'pandas']
Array with Spaces Between Characters: ['p y t h o n' 'n u m p y' 'p a n d a s']


**7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and divisio**

In [41]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

# Perform element-wise operations
addition = array1 + array2        # Element-wise addition
subtraction = array1 - array2     # Element-wise subtraction
multiplication = array1 * array2  # Element-wise multiplication
division = array1 / array2        # Element-wise division

# Print the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Division:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


**8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements**

In [42]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the results
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array**

To generate a NumPy array of 100 random integers between 0 and 1000 and then find all prime numbers in that array, you can follow these steps:

1.Generate the random integers using NumPy.

2.Create a function to check for prime numbers.

3.Use the function to filter and display the prime numbers from the array.

In [43]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

def is_prime(n):
    """Check if a number is prime."""
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Print the results
print("Random Integers:\n", random_integers)
print("Prime Numbers in the Array:", prime_numbers)

Random Integers:
 [842 942 138 222 750 315 187 858 812  35 408 864 615 369 467 543 305 215
 246 118 880 439 353 937  66 831 806 613 504 266 455 439 270 909 542 529
 522 737 204 742 801 989 559 837 456 419 653  86 916  74 619 247 885 958
 521 637 954 987 655 359 672 981 342 308  88  71 962 711 190 119 188 337
 164 486  55 411 592 870  79   9 824 402 902 627 306 284 763 467 495 693
  26 826  17 914 190 252 407 732 170 270]
Prime Numbers in the Array: [467, 439, 353, 937, 613, 439, 419, 653, 619, 521, 359, 71, 337, 79, 467, 17]


**10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages**


To create a NumPy array representing daily temperatures for a month and calculate the weekly averages, you can follow these steps:

1.Generate a NumPy array with random temperatu.res for 30 days (representing a month).

2.Reshape this array into weeks (assuming 4 weeks).

3.Calculate the weekly averages.

In [ ]:

import numpy as np

# Generate a NumPy array with random temperatures for 30 days
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.randint(32, 90, size=30)  # Fahrenheit

# Reshape the array into weeks (assuming 4 weeks)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the results
print("Daily Temperatures:")
print(daily_temperatures)

print("\nWeekly Temperatures:")
print(weekly_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)